parent=base
import=common/keycloak
locales=es
styles=css/agora.css
scripts=js/agora.js
meta=viewport==width=device-width,initial-scale=1 color-scheme==light dark
kcHtmlClass=agora
kcBodyClass=agora-cuerpo
kcLoginClass=agora-marco
kcHeaderClass=agora-encabezado
kcHeaderWrapperClass=agora-marca
kcFormCardClass=agora-tarjeta
kcFormHeaderClass=agora-tarjeta-encabezado
kcContentWrapperClass=agora-fila
kcFormGroupClass=agora-grupo
kcLabelClass=agora-etiqueta
kcLabelWrapperClass=agora-etiqueta-envoltura
kcInputClass=agora-control
kcInputWrapperClass=agora-control-envoltura
kcInputGroup=agora-control-grupo
kcInputErrorMessageClass=agora-error
kcInputHelperTextBeforeClass=agora-ayuda
kcInputHelperTextAfterClass=agora-ayuda
kcFormSettingClass=agora-opciones
kcFormOptionsClass=agora-opciones
kcFormOptionsWrapperClass=agora-opciones-envoltura
kcFormButtonsClass=agora-botones
kcFormButtonsWrapperClass=agora-botones
kcButtonClass=agora-boton
kcButtonPrimaryClass=agora-boton-primario
kcButtonSecondaryClass=agora-boton-secundario
kcButtonDefaultClass=agora-boton-secundario
kcButtonBlockClass=agora-boton-bloque
kcButtonLargeClass=agora-boton-grande
kcFormPasswordVisibilityButtonClass=agora-ver-clave
kcFormPasswordVisibilityIconShow=agora-icono-ojo
kcFormPasswordVisibilityIconHide=agora-icono-ojo-tachado
kcAlertClass=agora-aviso
kcAlertTitleClass=agora-aviso-texto
kcSignUpClass=agora-info
kcInfoAreaWrapperClass=agora-info-envoltura
kcFeedbackErrorIcon=
kcFeedbackWarningIcon=
kcFeedbackSuccessIcon=
kcFeedbackInfoIcon=
kcResetFlowIcon=agora-icono-reiniciar
kcSelectAuthListClass=agora-lista
kcSelectAuthListItemClass=agora-lista-elemento
kcCheckboxInputClass=agora-casilla
kcRadioClass=agora-radio
kcRadioInputClass=agora-radio-control
kcRadioLabelClass=agora-radio-etiqueta
kcLocaleMainClass=agora-oculto
