
ALTER DEFAULT PRIVILEGES FOR ROLE agora_migraciones IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO agora_app;

ALTER DEFAULT PRIVILEGES FOR ROLE agora_migraciones IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO agora_app;

ALTER DEFAULT PRIVILEGES FOR ROLE agora_migraciones IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO agora_app;

